async function resetAlertsToNormal(){await chrome.storage.local.set({...DEFAULTS,[GLOBAL_PROFILE_KEY]:'normal'});globalProfile='normal';await loadSettings();setSoundMessage(tr('resetAlertsDone'),'ok');}
async function resetAppearance(){appearance={...APPEARANCE_DEFAULTS};await chrome.storage.local.set({[APPEARANCE_KEY]:appearance});applyAppearance(appearance);populateFontSelect();refreshCustomSelects();}
async function resetAllSettings(){if(!confirm(tr('resetAllConfirm')))return;try{const r=await chrome.runtime.sendMessage({type:'reset-all-settings'});if(r?.ok===false)throw new Error(r.error||'Reset failed');location.reload();}catch(e){$('statusDetail').textContent=String(e);}}
function formatLogs(logs){if(!logs?.length)return tr('logEmpty');return logs.map(e=>`${e.ts} [${e.source}] ${String(e.level||'info').toUpperCase()} ${e.message}${e.details==null?'':` | ${JSON.stringify(e.details)}`}`).join('\n');}async function refreshLog(){const d=await chrome.storage.local.get(LOG_KEY),l=Array.isArray(d[LOG_KEY])?d[LOG_KEY]:[];$('log').textContent=formatLogs(l.slice(-100));}async function diagnosticsText(){const d=await chrome.storage.local.get([LOG_KEY,'uiLanguage','customSoundName',GLOBAL_PROFILE_KEY,SITE_SETTINGS_KEY,APPEARANCE_KEY,...SETTING_KEYS]),perms={};for(const s of SITE_API.SITE_CATALOG)perms[s.id]=await permissionGranted(s);return JSON.stringify({extension:'DoneBell',version:chrome.runtime.getManifest().version,exportedAt:new Date().toISOString(),uiLanguage:d.uiLanguage||'auto',globalProfile:d[GLOBAL_PROFILE_KEY]||'custom',settings:Object.fromEntries(SETTING_KEYS.map(k=>[k,d[k]??DEFAULTS[k]])),siteSettings:d[SITE_SETTINGS_KEY]||{},appearance:d[APPEARANCE_KEY]||APPEARANCE_DEFAULTS,sitePermissions:perms,browser:browserIdentity(),activeTab:activeTab?safePageIdentity(activeTab.url):null,currentStatus:currentStatus?{site:currentStatus.site,watching:Boolean(currentStatus.watching),mode:currentStatus.mode||null,completionActive:Boolean(currentStatus.completionActive),stopPresent:Boolean(currentStatus.stopPresent),autoStarted:Boolean(currentStatus.autoStarted)}:null},null,2)+`\n\n--- LOG ---\n${formatLogs(d[LOG_KEY]||[])}\n`;}async function copyLog(){const t=await diagnosticsText();await navigator.clipboard.writeText(t);$('statusDetail').textContent=tr('copied');}async function downloadLog(){const t=await diagnosticsText(),u=URL.createObjectURL(new Blob([t],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`donebell-log-${Date.now()}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}async function clearLog(){await chrome.storage.local.set({[LOG_KEY]:[]});await refreshLog();}
function safePageIdentity(url){try{const u=new URL(url);return{origin:u.origin,path:u.pathname};}catch{return null;}}
function browserIdentity(){const ua=navigator.userAgent||'';let m=ua.match(/Edg\/([\d.]+)/);if(m)return{name:'Edge',version:m[1]};m=ua.match(/Chrome\/([\d.]+)/);if(m)return{name:'Chrome/Chromium',version:m[1]};m=ua.match(/Firefox\/([\d.]+)/);if(m)return{name:'Firefox',version:m[1]};return{name:'Browser',version:'unknown'};}
async function publicBugReportText(){const full=await diagnosticsText(),browser=browserIdentity(),site=currentStatus?.site||SITE_API.siteForUrl(activeTab?.url||'');const header=[`DoneBell ${chrome.runtime.getManifest().version}`,`${browser.name} ${browser.version}`,`Site: ${site?.name||safePageIdentity(activeTab?.url)?.origin||'unknown'}`,`Mode: ${currentStatus?.mode||'none'}`,`Watching: ${Boolean(currentStatus?.watching)}`,`Completion active: ${Boolean(currentStatus?.completionActive)}`].join('\n');return `${header}\n\n--- DONEBELL DIAGNOSTICS ---\n${full}`;}
function feedbackLinks(){return globalThis.DoneBellLinks||{};}
function setFeedbackStatus(text,kind=''){const e=$('feedbackStatus');e.textContent=text||'';e.className=`small feedback-status ${kind||''}`;}
async function openExternal(url){if(!url)return false;try{await chrome.tabs.create({url});return true;}catch{return false;}}
function issueBaseUrl(repo){try{const u=new URL(repo);if(u.hostname!=='github.com')return null;return u.href.replace(/\/$/,'')+'/issues/new';}catch{return null;}}
async function reportProblem(){try{const report=await publicBugReportText();await navigator.clipboard.writeText(report);const repo=feedbackLinks().githubRepoUrl,base=issueBaseUrl(repo);if(!base){setFeedbackStatus(tr('reportCopiedNoLink'),'ok');return;}const browser=browserIdentity(),site=currentStatus?.site?.name||SITE_API.siteForUrl(activeTab?.url||'')?.name||'Web';const url=new URL(base);url.searchParams.set('title',`[Bug] ${site} — DoneBell ${chrome.runtime.getManifest().version}`);url.searchParams.set('body',`${tr('githubBugBody')}\n\n**DoneBell:** ${chrome.runtime.getManifest().version}\n**Browser:** ${browser.name} ${browser.version}\n**Site:** ${site}\n\n${tr('githubPasteDiagnostics')}`);await openExternal(url.href);setFeedbackStatus(tr('reportCopiedOpened'),'ok');}catch(e){setFeedbackStatus(String(e),'bad');}}
async function suggestIdea(){const base=issueBaseUrl(feedbackLinks().githubRepoUrl);if(!base){setFeedbackStatus(tr('feedbackLinkMissing'),'bad');return;}const url=new URL(base);url.searchParams.set('title','[Feature] ');url.searchParams.set('body',tr('githubFeatureBody'));await openExternal(url.href);}
async function supportDoneBell(){const url=feedbackLinks().supportUrl;if(!url){setFeedbackStatus(tr('supportLinkMissing'),'bad');return;}await openExternal(url);}
function refreshFeedbackAvailability(){const l=feedbackLinks();const support=$('supportDoneBell');support.hidden=!l.supportUrl;const repoOk=Boolean(issueBaseUrl(l.githubRepoUrl));$('reportProblem').classList.toggle('feedback-disabled',!repoOk);$('suggestIdea').classList.toggle('feedback-disabled',!repoOk);$('reportProblem').title=repoOk?'':tr('feedbackLinkMissing');$('suggestIdea').title=repoOk?'':tr('feedbackLinkMissing');}
async function changeLanguage(){uiLanguageSetting=$('languageSelect').value||'auto';await chrome.storage.local.set({uiLanguage:uiLanguageSetting});lang=I18N.resolveLanguage(uiLanguageSetting,navigator.language);localizeStatic();await loadSettings();renderStatus();await renderSites();}
async function init(){const d=await chrome.storage.local.get(['uiLanguage',GLOBAL_PROFILE_KEY,SITE_SETTINGS_KEY,APPEARANCE_KEY]);uiLanguageSetting=d.uiLanguage||'auto';lang=I18N.resolveLanguage(uiLanguageSetting,navigator.language);globalProfile=d[GLOBAL_PROFILE_KEY]||'custom';siteSettingsMap=d[SITE_SETTINGS_KEY]||{};appearance=normalizeAppearance(d[APPEARANCE_KEY]);applyAppearance(appearance);localizeStatic();setupCustomSelect('languageSelect','languageButton','languageMenu');setupCustomSelect('condition','conditionButton','conditionMenu');setupCustomSelect('fontFamilySelect','fontFamilyButton','fontFamilyMenu');refreshCustomSelects();$('languageSelect').addEventListener('change',changeLanguage);$('fontFamilySelect').addEventListener('change',()=>saveAppearance({fontFamily:$('fontFamilySelect').value}));$('fontSize').addEventListener('input',()=>saveAppearance({fontSize:Number($('fontSize').value)}));$('backgroundColor').addEventListener('input',()=>saveAppearance({backgroundColor:$('backgroundColor').value}));$('accentColor').addEventListener('input',()=>saveAppearance({accentColor:$('accentColor').value}));$('badgeBuiltinColor').addEventListener('input',()=>saveAppearance({badgeBuiltinColor:$('badgeBuiltinColor').value}));$('badgeDedicatedColor').addEventListener('input',()=>saveAppearance({badgeDedicatedColor:$('badgeDedicatedColor').value}));$('badgeGenericColor').addEventListener('input',()=>saveAppearance({badgeGenericColor:$('badgeGenericColor').value}));$('badgeStrength').addEventListener('input',()=>saveAppearance({badgeStrength:Number($('badgeStrength').value)}));$('resetAppearance').onclick=resetAppearance;$('resetAlerts').onclick=resetAlertsToNormal;$('resetAll').onclick=resetAllSettings;$('aiWatch').onclick=toggleAi;$('stopWatch').onclick=stopWatch;$('pickElement').onclick=pickElement;$('soundFile').onchange=saveSoundFile;$('resetSound').onclick=resetSound;$('testSound').onclick=testSound;$('stopSound').onclick=stopSound;$('volume').oninput=saveVolume;for(const k of BOOLEAN_KEYS)$(k).onchange=()=>saveBoolean(k);$('refreshLog').onclick=refreshLog;$('copyLog').onclick=copyLog;$('downloadLog').onclick=downloadLog;$('clearLog').onclick=clearLog;$('reportProblem').onclick=reportProblem;$('suggestIdea').onclick=suggestIdea;$('supportDoneBell').onclick=supportDoneBell;refreshFeedbackAvailability();await loadSettings();await refreshStatus();await renderSites();await refreshLog();}
init().catch(e=>{$('status').textContent=tr('connectFail');$('status').className='status bad';$('statusDetail').textContent=String(e);});
