const LOG_KEY='debugLogs',SITE_SETTINGS_KEY='siteSettings',GLOBAL_PROFILE_KEY='globalProfile',APPEARANCE_KEY='appearanceSettings',MAX_SOUND_BYTES=5*1024*1024;
const SETTING_KEYS=['soundEnabled','soundVolume','repeatSound','focusTab','stopOnTabFocus','showNotification','flashTitle','inPagePanel'],BOOLEAN_KEYS=['soundEnabled','repeatSound','focusTab','stopOnTabFocus','showNotification','flashTitle','inPagePanel'];
const DEFAULTS={soundEnabled:true,soundVolume:1,repeatSound:false,focusTab:false,stopOnTabFocus:false,showNotification:true,flashTitle:true,inPagePanel:true},PROFILE_IDS=['quiet','normal','urgent','custom'];
const APPEARANCE_DEFAULTS={fontFamily:'system',fontSize:14,backgroundColor:'#0d0d0f',accentColor:'#ffd42a',badgeBuiltinColor:'#38b35d',badgeDedicatedColor:'#ffbe24',badgeGenericColor:'#5591eb',badgeStrength:22};
const FONT_OPTIONS=[['system','System UI'],['segoeVariable','Segoe UI Variable'],['segoe','Segoe UI'],['calibri','Calibri'],['candara','Candara'],['corbel','Corbel'],['verdana','Verdana'],['tahoma','Tahoma'],['arial','Arial'],['trebuchet','Trebuchet MS'],['centuryGothic','Century Gothic'],['franklin','Franklin Gothic Medium'],['lucida','Lucida Sans Unicode'],['georgia','Georgia'],['noto','Noto Sans'],['yuGothic','Yu Gothic UI'],['meiryo','Meiryo UI'],['yahei','Microsoft YaHei UI'],['jhenghei','Microsoft JhengHei UI'],['malgun','Malgun Gothic'],['nirmala','Nirmala UI'],['cascadia','Cascadia Code'],['consolas','Consolas'],['courier','Courier New']];
const FONT_STACKS={system:'system-ui,-apple-system,"Segoe UI Variable","Segoe UI",sans-serif',segoeVariable:'"Segoe UI Variable","Segoe UI",system-ui,sans-serif',segoe:'"Segoe UI",system-ui,sans-serif',calibri:'Calibri,"Segoe UI",Arial,sans-serif',candara:'Candara,Calibri,"Segoe UI",sans-serif',corbel:'Corbel,Calibri,"Segoe UI",sans-serif',verdana:'Verdana,Geneva,sans-serif',tahoma:'Tahoma,Geneva,sans-serif',arial:'Arial,Helvetica,sans-serif',trebuchet:'"Trebuchet MS",Arial,sans-serif',centuryGothic:'"Century Gothic",Arial,sans-serif',franklin:'"Franklin Gothic Medium","Arial Narrow",Arial,sans-serif',lucida:'"Lucida Sans Unicode","Lucida Grande",sans-serif',georgia:'Georgia,"Times New Roman",serif',noto:'"Noto Sans","Segoe UI",Arial,sans-serif',yuGothic:'"Yu Gothic UI","Yu Gothic","Meiryo UI",sans-serif',meiryo:'"Meiryo UI",Meiryo,"Yu Gothic UI",sans-serif',yahei:'"Microsoft YaHei UI","Microsoft YaHei","Segoe UI",sans-serif',jhenghei:'"Microsoft JhengHei UI","Microsoft JhengHei","Segoe UI",sans-serif',malgun:'"Malgun Gothic","Segoe UI",sans-serif',nirmala:'"Nirmala UI","Segoe UI",sans-serif',cascadia:'"Cascadia Code","Cascadia Mono",Consolas,monospace',consolas:'Consolas,"Cascadia Mono",monospace',courier:'"Courier New",monospace'};
const $=id=>document.getElementById(id),I18N=globalThis.DoneBellI18n,SITE_API=globalThis.DoneBellSites;
let activeTab=null,currentStatus=null,uiLanguageSetting='auto',lang=I18N.resolveLanguage('auto',navigator.language),globalProfile='custom',siteSettingsMap={},appearance={...APPEARANCE_DEFAULTS};const tr=(k,v)=>I18N.t(lang,k,v);
const customSelects=new Map();
function setupCustomSelect(selectId,buttonId,menuId){const select=$(selectId),button=$(buttonId),menu=$(menuId);if(!select||!button||!menu)return;const api={refresh(){const selected=select.options[select.selectedIndex]||select.options[0];button.textContent=selected?.textContent||'';menu.innerHTML='';for(const option of select.options){const item=document.createElement('button');item.type='button';item.className='db-select-option';item.textContent=option.textContent;item.setAttribute('aria-selected',String(option.value===select.value));item.onclick=e=>{e.stopPropagation();select.value=option.value;api.close();api.refresh();select.dispatchEvent(new Event('change',{bubbles:true}));};menu.appendChild(item);}},close(){menu.hidden=true;button.setAttribute('aria-expanded','false');}};button.onclick=e=>{e.stopPropagation();for(const [id,a]of customSelects)if(id!==selectId)a.close();const open=menu.hidden;menu.hidden=!open;button.setAttribute('aria-expanded',String(open));if(open)api.refresh();};select.onchange=()=>api.refresh();customSelects.set(selectId,api);api.refresh();}
document.addEventListener('click',()=>{for(const a of customSelects.values())a.close();});const refreshCustomSelects=()=>{for(const a of customSelects.values())a.refresh();};
const conditionsMap=()=>({disappear:tr('conditionDisappear'),hidden:tr('conditionHidden'),textChange:tr('conditionTextChange'),enabled:tr('conditionEnabled'),disabled:tr('conditionDisabled')});
const profileName=id=>tr({quiet:'profileQuiet',normal:'profileNormal',urgent:'profileUrgent',custom:'profileCustom'}[id]||'profileCustom');
const profileHint=id=>tr({quiet:'profileQuietHint',normal:'profileNormalHint',urgent:'profileUrgentHint',custom:'profileCustomHint'}[id]||'profileCustomHint');
const supportLabel=s=>tr(s==='dedicated'?'supportDedicated':s==='generic'?'supportGeneric':'supportBuiltin'),supportClass=s=>s==='dedicated'?'support-dedicated':s==='generic'?'support-generic':'support-builtin';
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function normalizeHex(v,fallback){const x=String(v||'').trim();return /^#[0-9a-f]{6}$/i.test(x)?x.toLowerCase():fallback;}
function hexRgb(hex){const h=normalizeHex(hex,'#0d0d0f').slice(1);return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)];}
function rgbHex(rgb){return'#'+rgb.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('');}
function mixHex(a,b,t){const A=hexRgb(a),B=hexRgb(b);return rgbHex(A.map((v,i)=>v+(B[i]-v)*t));}
function luminance(hex){const c=hexRgb(hex).map(v=>v/255).map(v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4));return .2126*c[0]+.7152*c[1]+.0722*c[2];}
function normalizeAppearance(v){const a={...APPEARANCE_DEFAULTS,...(v&&typeof v==='object'?v:{})};if(!FONT_STACKS[a.fontFamily])a.fontFamily='system';a.fontSize=Math.max(12,Math.min(19,Number(a.fontSize)||14));a.backgroundColor=normalizeHex(a.backgroundColor,APPEARANCE_DEFAULTS.backgroundColor);a.accentColor=normalizeHex(a.accentColor,APPEARANCE_DEFAULTS.accentColor);a.badgeBuiltinColor=normalizeHex(a.badgeBuiltinColor,APPEARANCE_DEFAULTS.badgeBuiltinColor);a.badgeDedicatedColor=normalizeHex(a.badgeDedicatedColor,APPEARANCE_DEFAULTS.badgeDedicatedColor);a.badgeGenericColor=normalizeHex(a.badgeGenericColor,APPEARANCE_DEFAULTS.badgeGenericColor);a.badgeStrength=Math.max(8,Math.min(60,Number(a.badgeStrength)||22));return a;}
function applyAppearance(v){appearance=normalizeAppearance(v);const r=document.documentElement.style,bg=appearance.backgroundColor,light=luminance(bg)>.46,panel=mixHex(bg,light?'#000000':'#ffffff',.055),panel2=mixHex(bg,light?'#000000':'#ffffff',.09),control=mixHex(bg,light?'#000000':'#ffffff',.12),control2=mixHex(bg,light?'#000000':'#ffffff',.18);r.setProperty('--bg',bg);r.setProperty('--panel',panel);r.setProperty('--panel2',panel2);r.setProperty('--control',control);r.setProperty('--control2',control2);r.setProperty('--text',light?'#17171a':'#f4f4f5');r.setProperty('--muted',light?'rgba(0,0,0,.68)':'rgba(255,255,255,.72)');r.setProperty('--line',light?'rgba(0,0,0,.16)':'rgba(255,255,255,.14)');r.setProperty('--soft',light?'rgba(0,0,0,.055)':'rgba(255,255,255,.055)');r.setProperty('--accent',appearance.accentColor);document.documentElement.style.colorScheme=light?'light':'dark';r.setProperty('--font-family',FONT_STACKS[appearance.fontFamily]);r.setProperty('--base-size',`${appearance.fontSize}px`);r.setProperty('--badge-builtin',appearance.badgeBuiltinColor);r.setProperty('--badge-dedicated',appearance.badgeDedicatedColor);r.setProperty('--badge-generic',appearance.badgeGenericColor);r.setProperty('--badge-builtin-text',mixHex(appearance.badgeBuiltinColor,light?'#000000':'#ffffff',light?.54:.48));r.setProperty('--badge-dedicated-text',mixHex(appearance.badgeDedicatedColor,light?'#000000':'#ffffff',light?.56:.44));r.setProperty('--badge-generic-text',mixHex(appearance.badgeGenericColor,light?'#000000':'#ffffff',light?.54:.5));r.setProperty('--badge-fill',`${appearance.badgeStrength}%`);if($('fontSize')){$('fontSize').value=String(appearance.fontSize);$('fontSizeText').textContent=`${appearance.fontSize} px`;}if($('backgroundColor'))$('backgroundColor').value=appearance.backgroundColor;if($('accentColor'))$('accentColor').value=appearance.accentColor;if($('badgeBuiltinColor'))$('badgeBuiltinColor').value=appearance.badgeBuiltinColor;if($('badgeDedicatedColor'))$('badgeDedicatedColor').value=appearance.badgeDedicatedColor;if($('badgeGenericColor'))$('badgeGenericColor').value=appearance.badgeGenericColor;if($('badgeStrength')){$('badgeStrength').value=String(appearance.badgeStrength);$('badgeStrengthText').textContent=`${appearance.badgeStrength}%`;}if($('fontFamilySelect')){$('fontFamilySelect').value=appearance.fontFamily;customSelects.get('fontFamilySelect')?.refresh();}}
function populateFontSelect(){const s=$('fontFamilySelect');if(!s)return;s.innerHTML='';for(const[id,label]of FONT_OPTIONS){const o=document.createElement('option');o.value=id;o.textContent=label;s.appendChild(o);}s.value=appearance.fontFamily;}
async function saveAppearance(patch){appearance=normalizeAppearance({...appearance,...patch});applyAppearance(appearance);await chrome.storage.local.set({[APPEARANCE_KEY]:appearance});}
